/**
 * Declared output shapes for every tool.
 *
 * Without them a caller sees free text and has to infer what a result contains,
 * which is how a footnote gets read as the author's own words or a field gets
 * invented. Declaring the shape makes the distinctions this extension exists to
 * keep straight — matn vs footnote, printed page vs Shamela's automatic count,
 * present on disk vs merely catalogued — part of the contract.
 *
 * Two things govern how these are written.
 *
 * The protocol renders a declared shape with `additionalProperties: false`, so
 * a field a tool RETURNS but does not DECLARE makes the call fail. Declaring a
 * field that never appears costs nothing. The shapes are therefore generated
 * from each tool's own output interface and kept a superset: every field is
 * optional, and the ones carrying meaning we must not blur are typed.
 *
 * `tests/integration/output-schemas.test.ts` calls the tools and checks their
 * responses against these, so a field added later cannot rot the contract
 * silently — it fails in development instead of in someone's session.
 */

import { z } from "zod";

/** Added to counted payloads by renderResponse; declared once for every tool. */
const envelope = {
    total_count: z.number().optional(),
    returned_count: z.number().optional(),
    complete: z.boolean().optional(),
    truncated: z.boolean().optional(),
    truncation_message: z.string().optional(),
};

export const OUTPUT_SCHEMAS = {
    shamela_books_by_period: {
        total: z.number().optional(),
        returned: z.number().optional(),
        offset: z.number().optional(),
        has_more: z.boolean().optional(),
        next_offset: z.unknown().optional(),
        filter: z.unknown().optional(),
        composed_from: z.unknown().optional(),
        composed_to: z.unknown().optional(),
        died_from: z.unknown().optional(),
        died_to: z.unknown().optional(),
        category_id: z.unknown().optional(),
        downloaded_only: z.unknown().optional(),
        book_ids: z.unknown().optional(),
        books: z.array(z.unknown()).optional(),
        ...envelope,
    },
    shamela_get_author: {
        author_id: z.unknown().optional(),
        author_name: z.unknown().optional(),
        death_year: z.unknown().optional(),
        death_text: z.unknown().optional(),
        book_count: z.unknown().optional(),
        books: z.array(z.unknown()).optional(),
        ...envelope,
    },
    shamela_get_aya: {
        aya_id: z.unknown().optional(),
        surah: z.unknown().optional(),
        surah_name: z.unknown().optional(),
        aya: z.unknown().optional(),
        body: z.string().optional(),
        amiri: z.unknown().optional(),
        majma: z.unknown().optional(),
        ...envelope,
    },
    shamela_get_book: {
        book_id: z.number().optional(),
        book_name: z.string().optional(),
        category_id: z.unknown().optional(),
        category: z.unknown().optional(),
        book_type: z.unknown().optional(),
        book_type_label: z.unknown().optional(),
        book_date: z.unknown().optional(),
        printed: z.unknown().optional(),
        available: z.unknown().optional(),
        downloaded: z.boolean().optional(),
        content_status: z.string().optional(),
        authors: z.unknown().optional(),
        pdf_links: z.unknown().optional(),
        publication_date: z.unknown().optional(),
        edition: z.unknown().optional(),
        editor: z.unknown().optional(),
        publisher: z.unknown().optional(),
        sub_books: z.unknown().optional(),
        notes: z.array(z.string()).optional(),
        ...envelope,
    },
    shamela_get_book_parts: {
        book_id: z.number().optional(),
        book_name: z.string().optional(),
        is_multi_volume: z.unknown().optional(),
        total_pages: z.unknown().optional(),
        parts: z.unknown().optional(),
        ...envelope,
    },
    shamela_get_book_section: {
        book_id: z.number().optional(),
        book_name: z.string().optional(),
        author_name: z.unknown().optional(),
        title_id: z.unknown().optional(),
        title_text: z.unknown().optional(),
        start_page_id: z.unknown().optional(),
        end_page_id: z.unknown().optional(),
        total_pages_in_section: z.unknown().optional(),
        next_start_page_id: z.unknown().optional(),
        _display: z.unknown().optional(),
        pages: z.unknown().optional(),
        ...envelope,
    },
    shamela_get_books_for_hadith: {
        hadith_key: z.unknown().optional(),
        total: z.number().optional(),
        returned: z.number().optional(),
        results: z.array(z.unknown()).optional(),
        ...envelope,
    },
    shamela_get_citation: {
        formatted: z.unknown().optional(),
        style: z.unknown().optional(),
        components: z.unknown().optional(),
        notes: z.array(z.string()).optional(),
        ...envelope,
    },
    shamela_get_page: {
        book_id: z.number().optional(),
        book_name: z.string().optional(),
        author_name: z.unknown().optional(),
        page_id: z.number().optional(),
        printed_page: z.string().nullable().optional(),
        part: z.unknown().optional(),
        body: z.string().optional(),
        foot: z.string().optional(),
        comment: z.string().optional(),
        body_part: z.unknown().optional(),
        body_total_parts: z.unknown().optional(),
        body_has_more: z.unknown().optional(),
        _display: z.unknown().optional(),
        prev_page_id: z.unknown().optional(),
        next_page_id: z.unknown().optional(),
        containing_titles: z.unknown().optional(),
        category_path: z.unknown().optional(),
        citation: z.string().optional(),
        citation_auto_numbered: z.boolean().optional(),
        ...envelope,
    },
    shamela_get_page_services: {
        book_id: z.number().optional(),
        page_id: z.number().optional(),
        has_services: z.unknown().optional(),
        ayat: z.unknown().optional(),
        hadeeth: z.unknown().optional(),
        esnad: z.unknown().optional(),
        raw: z.unknown().optional(),
        ...envelope,
    },
    shamela_get_pages_range: {
        citation_auto_numbered: z.boolean().optional(),
        book_id: z.number().optional(),
        book_name: z.string().optional(),
        author_name: z.unknown().optional(),
        start_page_id: z.unknown().optional(),
        count: z.unknown().optional(),
        has_more: z.boolean().optional(),
        next_start_page_id: z.unknown().optional(),
        _display: z.unknown().optional(),
        pages: z.unknown().optional(),
        ...envelope,
    },
    shamela_get_tafseer_of_aya: {
        index_rows: z.number().optional(),
        aya_id: z.unknown().optional(),
        surah: z.unknown().optional(),
        surah_name: z.unknown().optional(),
        aya: z.unknown().optional(),
        total: z.number().optional(),
        returned: z.number().optional(),
        coverage_note: z.unknown().optional(),
        results: z.array(z.unknown()).optional(),
        ...envelope,
    },
    shamela_get_tafseer_texts: {
        total_from_service: z.number().optional(),
        total_from_titles: z.number().optional(),
        aya_id: z.unknown().optional(),
        surah: z.unknown().optional(),
        surah_name: z.unknown().optional(),
        aya: z.unknown().optional(),
        total_indexed: z.unknown().optional(),
        fetched: z.unknown().optional(),
        sources: z.unknown().optional(),
        remaining_book_ids: z.unknown().optional(),
        _display: z.unknown().optional(),
        note: z.unknown().optional(),
        ...envelope,
    },
    shamela_get_toc: {
        book_id: z.number().optional(),
        book_name: z.string().optional(),
        mode: z.unknown().optional(),
        parent_id: z.unknown().optional(),
        depth: z.unknown().optional(),
        titles: z.unknown().optional(),
        ancestor_chain: z.unknown().optional(),
        ...envelope,
    },
    shamela_guide: {
        section: z.unknown().optional(),
        available_sections: z.unknown().optional(),
        text: z.unknown().optional(),
        notes: z.array(z.string()).optional(),
        ...envelope,
    },
    shamela_health: {
        aya_index: z.unknown().optional(),
        server_version: z.unknown().optional(),
        status: z.string().optional(),
        catalog_books: z.unknown().optional(),
        catalog_authors: z.unknown().optional(),
        categories: z.unknown().optional(),
        downloaded_books: z.unknown().optional(),
        flagged_books: z.unknown().optional(),
        flagged_file_missing: z.unknown().optional(),
        orphan_files: z.unknown().optional(),
        disk_scan_fell_back: z.unknown().optional(),
        readable_spot_check: z.unknown().optional(),
        readable: z.unknown().optional(),
        unreadable_book_ids: z.unknown().optional(),
        search_index: z.unknown().optional(),
        page_docs: z.unknown().optional(),
        book_docs: z.unknown().optional(),
        author_docs: z.unknown().optional(),
        probe_query: z.unknown().optional(),
        probe_hits: z.unknown().optional(),
        error: z.unknown().optional(),
        notes: z.array(z.string()).optional(),
        ...envelope,
    },
    shamela_list_categories: {
        total: z.number().optional(),
        downloaded_total: z.unknown().optional(),
        categories: z.unknown().optional(),
        ...envelope,
    },
    shamela_list_downloaded_books: {
        total: z.number().optional(),
        returned: z.number().optional(),
        offset: z.number().optional(),
        has_more: z.boolean().optional(),
        next_offset: z.unknown().optional(),
        filtered_category_id: z.unknown().optional(),
        library_by_category: z.unknown().optional(),
        books: z.array(z.unknown()).optional(),
        ...envelope,
    },
    shamela_list_tafsirs_for_aya: {
        index_pending_book_ids: z.unknown().optional(),
        aya_id: z.unknown().optional(),
        surah: z.unknown().optional(),
        surah_name: z.unknown().optional(),
        aya: z.unknown().optional(),
        totals: z.unknown().optional(),
        indexed_covers: z.unknown().optional(),
        indexed_no_entry_for_this_aya: z.unknown().optional(),
        not_indexed_coverage_unknown: z.unknown().optional(),
        note: z.unknown().optional(),
        books: z.array(z.unknown()).optional(),
        ...envelope,
    },
    shamela_resolve: {
        query: z.string().optional(),
        normalized_tokens: z.unknown().optional(),
        books: z.array(z.unknown()).optional(),
        authors: z.unknown().optional(),
        ...envelope,
    },
    shamela_root_stats: {
        root: z.unknown().optional(),
        normalized_tokens: z.unknown().optional(),
        total_hits: z.number().optional(),
        total_counted: z.unknown().optional(),
        books_matched: z.unknown().optional(),
        coverage_capped: z.unknown().optional(),
        coverage_cap: z.unknown().optional(),
        coverage_basis: z.unknown().optional(),
        scope_count: z.unknown().optional(),
        accuracy_note: z.unknown().optional(),
        by_category: z.unknown().optional(),
        by_century: z.unknown().optional(),
        by_book: z.unknown().optional(),
        by_author: z.unknown().optional(),
        ...envelope,
    },
    shamela_search_authors: {
        total_hits: z.number().optional(),
        returned: z.number().optional(),
        offset: z.number().optional(),
        has_more: z.boolean().optional(),
        next_offset: z.unknown().optional(),
        query: z.string().optional(),
        normalized_tokens: z.unknown().optional(),
        results: z.array(z.unknown()).optional(),
        ...envelope,
    },
    shamela_search_books: {
        total_hits: z.number().optional(),
        returned: z.number().optional(),
        offset: z.number().optional(),
        has_more: z.boolean().optional(),
        next_offset: z.unknown().optional(),
        query: z.string().optional(),
        normalized_tokens: z.unknown().optional(),
        coverage: z.unknown().optional(),
        by_century: z.unknown().optional(),
        results: z.array(z.unknown()).optional(),
        ...envelope,
    },
    shamela_search_boolean: {
        all_of: z.unknown().optional(),
        any_of: z.unknown().optional(),
        none_of: z.unknown().optional(),
        scope_count: z.unknown().optional(),
        total_in_window: z.unknown().optional(),
        returned: z.number().optional(),
        offset: z.number().optional(),
        has_more: z.boolean().optional(),
        next_offset: z.unknown().optional(),
        candidate_cap_hit: z.unknown().optional(),
        none_of_within_window: z.unknown().optional(),
        subqueries: z.unknown().optional(),
        notes: z.array(z.string()).optional(),
        results: z.array(z.unknown()).optional(),
        ...envelope,
    },
    shamela_search_exact: {
        query: z.string().optional(),
        preserve: z.unknown().optional(),
        total_candidates_scanned: z.unknown().optional(),
        candidate_cap_hit: z.unknown().optional(),
        returned: z.number().optional(),
        results: z.array(z.unknown()).optional(),
        ...envelope,
    },
    shamela_search_hadith: {
        query: z.string().optional(),
        total_text_matches: z.unknown().optional(),
        pages_scanned: z.unknown().optional(),
        matches: z.unknown().optional(),
        takhrij: z.unknown().optional(),
        books: z.array(z.unknown()).optional(),
        ...envelope,
    },
    shamela_search_pages: {
        total_hits: z.number().optional(),
        returned: z.number().optional(),
        offset: z.number().optional(),
        has_more: z.boolean().optional(),
        next_offset: z.unknown().optional(),
        query: z.string().optional(),
        normalized_tokens: z.unknown().optional(),
        scope_count: z.unknown().optional(),
        coverage: z.unknown().optional(),
        by_category: z.unknown().optional(),
        by_century: z.unknown().optional(),
        by_book: z.unknown().optional(),
        by_author: z.unknown().optional(),
        results: z.array(z.unknown()).optional(),
        ...envelope,
    },
    shamela_search_phrase: {
        mode: z.unknown().optional(),
        query: z.string().optional(),
        distance: z.unknown().optional(),
        total_hits: z.number().optional(),
        total_candidates_scanned: z.unknown().optional(),
        candidate_cap_hit: z.unknown().optional(),
        returned: z.number().optional(),
        offset: z.number().optional(),
        has_more: z.boolean().optional(),
        next_offset: z.unknown().optional(),
        results: z.array(z.unknown()).optional(),
        ...envelope,
    },
    shamela_search_quran: {
        total_hits: z.number().optional(),
        returned: z.number().optional(),
        offset: z.number().optional(),
        has_more: z.boolean().optional(),
        next_offset: z.unknown().optional(),
        query: z.string().optional(),
        normalized_tokens: z.unknown().optional(),
        total_hits_complete: z.unknown().optional(),
        suggestions: z.array(z.string()).optional(),
        results: z.array(z.unknown()).optional(),
        ...envelope,
    },
    shamela_search_titles: {
        total_hits: z.number().optional(),
        returned: z.number().optional(),
        offset: z.number().optional(),
        has_more: z.boolean().optional(),
        next_offset: z.unknown().optional(),
        query: z.string().optional(),
        normalized_tokens: z.unknown().optional(),
        results: z.array(z.unknown()).optional(),
        ...envelope,
    },
    shamela_suggest_download: {
        query: z.string().optional(),
        total: z.number().optional(),
        returned: z.number().optional(),
        downloaded_count: z.unknown().optional(),
        available_count: z.unknown().optional(),
        unavailable_count: z.unknown().optional(),
        results: z.array(z.unknown()).optional(),
        next_steps: z.array(z.string()).optional(),
        notes: z.array(z.string()).optional(),
        ...envelope,
    },
} as const;

export type ToolWithOutputSchema = keyof typeof OUTPUT_SCHEMAS;
